#!/usr/bin/env python3

import pathlib

def configure(cfg):
    cfg.env.CMAKE_MIN_VERSION = '3.10'
    cfg.load('cmake')

def build(bld):
    MIP_SDK_FOLDER = pathlib.Path("modules") / "mip_sdk"
    src_dir = bld.srcnode.find_node(str(MIP_SDK_FOLDER))
    build_dir = bld.bldnode.make_node(str(MIP_SDK_FOLDER))

    # cmake configuration
    mip = bld.cmake(
        name='mip',
        cmake_src=src_dir,
        cmake_bld=build_dir,
        # cmake_vars=dict(
        #     CMAKE_BUILD_TYPE='Release',
        #     # WITH_SERIAL=False
        # ),
    )
    
    mip.build('mip')
