#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_AIR_SENSOR_ENABLED
#define AP_AIR_SENSOR_ENABLED 1
#endif

#ifndef AP_AIR_SENSOR_AIRSPEED_ENABLED
#define AP_AIR_SENSOR_AIRSPEED_ENABLED AP_AIR_SENSOR_ENABLED
#endif

#ifndef AP_AIR_SENSOR_WIND_VANE_ENABLED
#define AP_AIR_SENSOR_WIND_VANE_ENABLED AP_AIR_SENSOR_ENABLED
#endif

#ifndef AP_AIR_SENSOR_SCRIPTING_ENABLED
#define AP_AIR_SENSOR_SCRIPTING_ENABLED AP_AIR_SENSOR_ENABLED
#endif
